CREATE TABLE IF NOT EXISTS users
(
    id SERIAL  PRIMARY KEY,
    name  VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS contacts
(
    id SERIAL  PRIMARY KEY,
    name  VARCHAR(50) NOT NULL,
    phoneNumber VARCHAR NOT NULL
);